const Enums = {
  selectOptionsType: {
    Sports: 1,
    Casino: 2,
  },
  
  diamondSelectPages: {
    "HOME": 1,
    "IN PLAY": 2,
    "ELECTIONS": 3,
    "CRICKET": 4,
    "FOOT BALL": 5,
    "TENNIS": 6,
    "GREY HOUND": 7,
    "HOURSE RACING": 8,
    "CASINO": 9,
    "SOCCER": 10,

    // "MULTI MARKET": 10,
    // "BASCKET BALL": 12,
    // "KABADDI": 13,
    // "ICE HOCKEY": 14,
    // "VOLLEY BALL": 15,
    // "TABLE TENNIS": 16,
  },
  sparkbookSelectPages: {
    "IN PLAY": 1,
    "CRICKET": 2,
    "FOOT BALL": 3,
    "TENNIS": 4,
    "HOURSE RACING": 5,
    "GREY HOUND": 6,
    "BASCKET BALL": 7,
    "Indian CASINO": 8,
    "CASINO": 9,
    "BASE BALL": 10,
    "MULTI MARKET": 11,
    "SPORTS BOOK":12,
    "EXCHANGE":13,
    "VIRTUAL SPORTS":14,
    "HOME":15,
  },

  nineExchangeSelectPages: {
    "IN PLAY": 1,
    "CRICKET": 2,
    "FOOT BALL": 3,
    "TENNIS": 4,
    "GREY HOUND": 5,
    "BADMINTON":6,
    "HOURSE RACING": 7,
    "KABADDI": 8,
    "CASINO": 9,
    // "MULTI MARKET": 10,
    // "SOCCER": 11,
    // "BASCKET BALL": 12,
    
    // "ICE HOCKEY": 14,
    // "VOLLEY BALL": 15,
    // "TABLE TENNIS": 16,
  },
  texchangeSelectPages: {
    "HOME": 1,
    // "IN PLAY": 2,
    // "ELECTIONS": 3,
    // "CRICKET": 4,
    // "FOOT BALL": 5,
    // "TENNIS": 6,
    // "GREY HOUND": 7,
    // "HOURSE RACING": 8,
    // "CASINO": 9,
    // "MULTI MARKET": 10,
    // "SOCCER": 11,
    // "BASCKET BALL": 12,
    // "KABADDI": 13,
    // "ICE HOCKEY": 14,
    // "VOLLEY BALL": 15,
    // "TABLE TENNIS": 16,
  },
  diamondSelectPlace: {
    MAIN: 1,
  },
  sparkbookSelectPlace: {
    MAIN: 1,
    SERIES: 2,
  },
  nineExchangeSelectPlace: {
    MAIN: 1,
  },
  texchangeSelectPlace: {
    MAIN: 1,
  },
 
};

export default Enums;
