export const Images = {
  LoginImageOne: "assets/login_image_one.png",
  LoginImageTwo: "assets/login_image_two.png",
  loginUserImages: "assets/loginUser.png",
  loginUserLock: "assets/loginPassword.png",
  S7Logo: "/assets/S7_Logo.png",
  ProfileImage: "/assets/Profile_Image.png",
  addManagementPopup: "assets/popup_image.png",
  dashboardProfile: "assets/dasboard_profile.png",
  ChatIcon: "/assets/Chat_Icon.png",
  Poster1: "/assets/poster1.png",
  Poster2: "/assets/poster2.png",
  Casino1: "/assets/casino1.png",
  Cricket1: "/assets/cricket1.png",
  adminProfileBg: "assets/admin_profile_bg.png",
  adminProfileShareRevenue: "/assets/director_admin_profile_share-revenue.png",
  adminProfileTotalPaid: "/assets/director_admin_profile_total-paid.png",
  adminProfileNetProfit: "/assets/director_admin_profile_net-profit.png",
  adminProfileTotalAdmins: "/assets/director_admin_profile_total-admins.png",
  adminProfileTotalUsers: "/assets/director_admin_profile_total-users.png",
  adminProfileBuyingChips: "/assets/director_admin_profile_buying-chips.png",
  adminProfileExposer: "/assets/director_admin_profile_exposer.png",
  adminProfileAvailableChips:
    "/assets/director_admin_profile_downline-available-chips.png",
  adminProfileBalanceChips: "/assets/director_admin_profile_balance-chips.png",
  adminProfileDownlinePlChips:
    "/assets/director_admin_profile_downline-available-chips.png",
  qnmark: "/assets/question-mark 1.png",
  cricket: "/assets/match.png",
  match: "/assets/match2.png",
  promotion2: "/assets/promotion2.jpg",
  promotion3: "/assets/promotion3.png",
  promotion4: "/assets/promotion4.png",
  promotion5: "/assets/promotion5.png",
  promotion6: "/assets/promotion6.png",
  promotion7: "/assets/promotion7.png",
  promotion8: "/assets/promotion8.png",
  promotion9: "/assets/promotion9.png",
  promotion10: "/assets/promotion10.png",
  promotion11: "/assets/promotion11.png",
  TourBlueFlag: "/assets/tour_blue_flag.png",
  TourGreenFlag: "/assets/tour_green_flag.png",
  TourMarket: "/assets/tour_market.png",
  TourPrize: "/assets/tour_prize.png",
  TourSportsSoccer: "/assets/tour_sports_soccer.png",
  TourYellowCard: "/assets/tour_yellow_card.png",
  TourScheduleClock: "/assets/tour_schedule.png",

};
